# DQN Hyperparameter Tuning Configuration for Optuna
# This file defines hyperparameters to tune using Bayesian Optimization

# Global settings for hyperparameter tuning
reduced_timesteps_factor: 1.0  # Run each training for 15% of the timesteps defined in base config

# Bayesian Optimization Configuration with Optuna
bayesian_optimization:
  # Core DQN Parameters
  "model.buffer_size":
    distribution: "int_uniform"
    min: 50000
    max: 1000000
  
  "model.learning_starts":
    distribution: "int_uniform"
    min: 50000
    max: 500000
  
  "model.batch_size":
    distribution: "int_uniform"
    min: 32
    max: 512
  
  "model.learning_rate":
    distribution: "loguniform"
    min: 0.000001
    max: 0.001
  
  "model.gamma":
    distribution: "uniform"
    min: 0.5
    max: 0.999
  
  "model.train_freq":
    distribution: "int_uniform"
    min: 1
    max: 1000
  
  "model.target_update_interval":
    distribution: "int_uniform"
    min: 500
    max: 50000
  
  "model.exploration_fraction":
    distribution: "uniform"
    min: 0.1
    max: 0.9
  
  "model.exploration_final_eps":
    distribution: "loguniform"
    min: 0.01
    max: 0.2